# Generated by Django 4.1 on 2022-09-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotifyrec", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SongRec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track", models.TextField()),
                ("trackURI", models.TextField()),
                ("artist", models.TextField()),
                ("album", models.TextField()),
                ("albumURI", models.TextField()),
                ("similarity", models.FloatField()),
            ],
        ),
    ]
