# Generated by Django 4.1 on 2022-09-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotifyrec", "0002_songrec"),
    ]

    operations = [
        migrations.AddField(
            model_name="songrec",
            name="artistURI",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="songrec",
            name="album",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="songrec",
            name="albumURI",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="songrec",
            name="artist",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="songrec",
            name="similarity",
            field=models.FloatField(default=""),
        ),
        migrations.AlterField(
            model_name="songrec",
            name="track",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="songrec",
            name="trackURI",
            field=models.TextField(default=""),
        ),
    ]
