# Generated by Django 4.1 on 2022-09-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotifyrec", "0003_songrec_artisturi_alter_songrec_album_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogMessage",
        ),
        migrations.RemoveField(
            model_name="songrec",
            name="albumURI",
        ),
        migrations.RemoveField(
            model_name="songrec",
            name="artistURI",
        ),
        migrations.AlterField(
            model_name="songrec",
            name="similarity",
            field=models.FloatField(default=0.0),
        ),
    ]
